# Pre-defined trainning deckes
class Deck:
    deck_list = []
    deck_list.append({"Class": 9,  # WARLOCK
                    "Deck": ["Soulfire",
                            "Soulfire",
                            "Abusive Sergeant",
                            "Abusive Sergeant",
                            "Argent Squire",
                            "Argent Squire",
                            "Flame Imp",
                            "Flame Imp",
                            "Leper Gnome",
                            "Leper Gnome",
                            "Mortal Coil",
                            "Mortal Coil",
                            "Voidwalker",
                            "Voidwalker",
                            "Young Priestess",
                            "Young Priestess",
                            "Dire Wolf Alpha",
                            "Dire Wolf Alpha",
                            "Knife Juggler",
                            "Knife Juggler",
                            "Harvest Golem",
                            "Harvest Golem",
                            "Shattered Sun Cleric",
                            "Shattered Sun Cleric",
                            "Dark Iron Dwarf",
                            "Dark Iron Dwarf",
                            "Defender of Argus",
                            "Defender of Argus",
                            "Doomguard",
                            "Doomguard",
                            ]})